In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader


import pandas as pd
import numpy as np

In [3]:
df_icu = pd.read_csv('../ICUSTAYS.csv')
df_pat = pd.read_csv('../PATIENTS.csv')
df_adm = pd.read_csv('../ADMISSIONS.csv')
df_diag = pd.read_csv('../DIAGNOSES_ICD.csv')
df_adm['DISCHTIME'].fillna('0',inplace=True)
df_icu.OUTTIME.fillna('0',inplace=True)

In [4]:
#Mortality Calculation

#Date of Death is before ICU Stay or Hospital Discharge for all Patients to find mortality count
all_pat = []
all_visits = []
all_diags = []
mortality = []
dead = False
# df_mort = df_pat[~df_pat.DOD.isnull()]
for i, row in df_pat.iterrows():
    
    pid = row['SUBJECT_ID']
#     print(pid)
    if ~df_pat[df_pat.SUBJECT_ID == pid].DOD.isnull().values[0]:
        ot = max(df_icu[df_icu.SUBJECT_ID ==pid].OUTTIME.values, default='0')
#         ot = pd.to_datetime(ot).reset_index(drop=True)
        dis_time = max(df_adm[df_adm.SUBJECT_ID == pid].DISCHTIME.values, default='0')
        dod = df_pat[df_pat.SUBJECT_ID == pid].DOD.values[0]
#         print(ot, dis_time, dod)
        dead = (dod <= ot) or (dod <= dis_time)
    if dead:
        mortality.append(1)
    else: 
        mortality.append(0)
    all_pat.append(pid)
    vids = list(df_adm[df_adm.SUBJECT_ID == pid]['HADM_ID'])
    all_visits.append(vids)
    pat_diags = []
    for v in vids:
        diags = list(df_diag[(df_diag.SUBJECT_ID == pid) & (df_diag.HADM_ID == v)]['ICD9_CODE'])
        pat_diags.append(diags)
    all_diags.append(pat_diags)
    dead = False

In [5]:
x = np.array(mortality)
ind = np.where(x == 1)[0]
dead_pat_in_hosp = [all_pat[i] for i in ind]
len(dead_pat_in_hosp)

df_mort = df_pat[~df_pat.DOD.isnull()]
len(df_mort)
mort_pat = list(df_mort.SUBJECT_ID.values)
unmatched_pat = [d for d in mort_pat if d not in dead_pat_in_hosp]
print(f"Patient died after hospital admission is {len(unmatched_pat)} \
        and cohort mortality is {(len(dead_pat_in_hosp)/len(all_pat))*100}")

Patient died after hospital admission is 9872         and cohort mortality is 12.654772141014616


In [6]:
#Get dictionary index for all ICD9 codes
icd_uniq = df_diag.ICD9_CODE.unique()
# icd_uniq = ['A', 'B', 'A']
icd_dic = {}
i = 0
for code in icd_uniq:
    icd_dic[code] = i
    i += 1
len(icd_dic)

6985

In [7]:
print("Patient ID:", all_pat[3])
print("Dead:", mortality[3])
print("# of visits:", len(all_visits[3]))
for visit in range(len(all_visits[3])):
    print(f"\t{visit}-th visit id:", all_visits[3][visit])
    print(f"\t{visit}-th visit diagnosis labels:", all_diags[3][visit])
#     print(f"\t{visit}-th visit diagnosis codes:", [rtypes[label] for label in seqs[3][visit]])

Patient ID: 252
Dead: 0
# of visits: 2
	0-th visit id: 190159
	0-th visit diagnosis labels: ['5712', '45620', '5780', '51881', '78559', '5722', '7895', '45341', '5990', '5849', '30500', '2867', '2761', '2875', '486', '5997', '8670', '2639', '2851', '5723', '34831', '2738', '5798', '0701', '3051', 'V1301', 'E8796']
	1-th visit id: 193470
	1-th visit diagnosis labels: ['5712', '45620', '7895', '2851', '3575']


In [8]:
from torch.utils.data import Dataset


class CustomDataset(Dataset):
    
    def __init__(self, seqs, mortality):
        
        """
        TODO: Store `seqs`. to `self.x` and `hfs` to `self.y`.
        
        Note that you DO NOT need to covert them to tensor as we will do this later.
        Do NOT permute the data.
        """
        
        # your code here
        self.x = seqs
        self.y = mortality
#         raise NotImplementedError
    
    def __len__(self):
        
        """
        TODO: Return the number of samples (i.e. patients).
        """
        
        # your code here
        return len(self.y)
#         raise NotImplementedError
    
    def __getitem__(self, index):
        
        """
        TODO: Generates one sample of data.
        
        Note that you DO NOT need to covert them to tensor as we will do this later.
        """
        
        # your code here
        seq = self.x[index]
        hf = self.y[index]

        return seq, hf
#         raise NotImplementedError
        

dataset = CustomDataset(all_diags, mortality)

In [9]:
num_visits = [len(patient) for patient in all_visits]
num_codes = [len(visit) for patient in all_diags for visit in patient]
max_num_visits = max(num_visits)
max_num_codes = max(num_codes)
max_num_visits, max_num_codes

(42, 39)

In [10]:
def collate_fn(data):
    
    sequences, labels = zip(*data)
    y = torch.tensor(labels, dtype=torch.int64)
    num_patients = len(sequences)
    num_visits = [len(patient) for patient in sequences]
    num_codes = [len(visit) for patient in sequences for visit in patient]
    max_num_visits = 42 #max(num_visits)
    max_num_codes = 39 #max(num_codes)
#     print(max_num_visits, max_num_codes, len(y) )
    x = torch.zeros((num_patients, max_num_visits, max_num_codes), dtype=torch.float)
    for i_patient, patient in enumerate(sequences):
        for j_visit, visit in enumerate(patient):
            for k_diag, diag in enumerate(visit):
                if diag != diag:
#                     print(diag, i_patient, j_visit,k_diag) 
                    continue
                else: x[i_patient, j_visit,k_diag ] =icd_dic[diag]
#     x = x.type(torch.LongTensor)
#     y = y.type(torch.LongTensor)
    return x, y


In [11]:
from torch.utils.data.dataset import random_split

split = int(len(dataset)*0.7)

lengths = [split, len(dataset) - split]
train_dataset, val_test_dataset = random_split(dataset, lengths)


split = int(len(val_test_dataset)*0.7)
lengths = [split, len(val_test_dataset) - split]
val_dataset, test_dataset = random_split(val_test_dataset, lengths)


print("Length of train dataset:", len(train_dataset))
print("Length of val dataset:", len(val_dataset))
print("Length of test dataset:", len(test_dataset))

Length of train dataset: 32563
Length of val dataset: 9769
Length of test dataset: 4188


In [12]:
def load_data(train_dataset, val_dataset, test_dataset, batch_size, collate_fn):
    batch_size = batch_size
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, collate_fn=collate_fn)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, collate_fn=collate_fn)
    
    return train_loader, val_loader, test_loader

batch_size = 128
train_loader, val_loader, test_loader = load_data(train_dataset, val_dataset, test_dataset, batch_size, collate_fn)

in_feature = 39
seq_len = 42
n_heads = 32
factor = 5 # M - dense interpolation factor
num_class = 2
num_layers = 1 #N


In [21]:
from sand_144 import SAnD

In [22]:
clf = sand_144.MyNeuralNetworkClassifier(
    SAnD(in_feature, seq_len, n_heads, factor, num_class, num_layers),
    nn.CrossEntropyLoss(),
    optim.Adam, optimizer_config={"lr": 1e-5, "betas": (0.9, 0.98), "eps": 4e-09, "weight_decay": 5e-4},
)


In [23]:
# training network
clf.fit(
    {"train": train_loader,
     "val": val_loader},
     epochs= 1
)


Training - Epochs: 001/001:   1%|         | 256/32563 [00:00<00:16, 2014.64it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   2%|▏        | 512/32563 [00:00<00:22, 1449.19it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   3%|▎       | 1024/32563 [00:00<00:21, 1453.61it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   4%|▎       | 1280/32563 [00:00<00:21, 1457.83it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   6%|▍       | 1792/32563 [00:01<00:21, 1462.17it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   6%|▌       | 2048/32563 [00:01<00:20, 1460.94it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   8%|▋       | 2560/32563 [00:01<00:20, 1458.50it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:   9%|▋       | 2816/32563 [00:02<00:20, 1467.26it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  10%|▊       | 3328/32563 [00:02<00:20, 1436.55it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  11%|▉       | 3584/32563 [00:02<00:21, 1366.19it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  12%|▉       | 3840/32563 [00:02<00:20, 1385.42it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  13%|█       | 4352/32563 [00:03<00:20, 1410.17it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  14%|█▏      | 4608/32563 [00:03<00:19, 1403.16it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  16%|█▎      | 5120/32563 [00:03<00:19, 1404.75it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  17%|█▎      | 5376/32563 [00:03<00:21, 1242.52it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  18%|█▍      | 5888/32563 [00:04<00:20, 1308.87it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  19%|█▌      | 6144/32563 [00:04<00:20, 1298.35it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  20%|█▋      | 6656/32563 [00:04<00:19, 1339.48it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  21%|█▋      | 6912/32563 [00:05<00:19, 1322.78it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  23%|█▊      | 7424/32563 [00:05<00:18, 1356.83it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  24%|█▉      | 7680/32563 [00:05<00:18, 1318.70it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  24%|█▉      | 7936/32563 [00:05<00:19, 1264.72it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  25%|██      | 8192/32563 [00:06<00:20, 1201.16it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  26%|██      | 8448/32563 [00:06<00:21, 1138.37it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  27%|██▏     | 8704/32563 [00:06<00:21, 1112.94it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  28%|██▏     | 8960/32563 [00:06<00:20, 1126.83it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  28%|██▎     | 9216/32563 [00:06<00:20, 1166.44it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  29%|██▎     | 9472/32563 [00:07<00:20, 1138.60it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  30%|██▍     | 9856/32563 [00:07<00:17, 1275.32it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  31%|██▏    | 10112/32563 [00:07<00:16, 1322.06it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  33%|██▎    | 10624/32563 [00:07<00:16, 1368.84it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  33%|██▎    | 10880/32563 [00:08<00:15, 1411.29it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])


Training - Epochs: 001/001:  35%|██▍    | 11392/32563 [00:08<00:15, 1383.03it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  36%|██▌    | 11648/32563 [00:08<00:14, 1401.83it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  37%|██▌    | 12160/32563 [00:09<00:14, 1435.78it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  38%|██▋    | 12416/32563 [00:09<00:13, 1447.93it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  40%|██▊    | 12928/32563 [00:09<00:13, 1479.67it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  40%|██▊    | 13184/32563 [00:09<00:13, 1468.15it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  42%|██▉    | 13696/32563 [00:10<00:12, 1451.84it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  43%|██▉    | 13952/32563 [00:10<00:13, 1414.35it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  44%|███    | 14464/32563 [00:10<00:12, 1437.42it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  45%|███▏   | 14720/32563 [00:10<00:12, 1437.49it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  47%|███▎   | 15232/32563 [00:11<00:12, 1430.32it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  48%|███▎   | 15488/32563 [00:11<00:11, 1429.24it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  49%|███▍   | 16000/32563 [00:11<00:11, 1458.00it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  50%|███▍   | 16256/32563 [00:11<00:11, 1405.86it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  51%|███▌   | 16768/32563 [00:12<00:10, 1437.01it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  52%|███▋   | 17024/32563 [00:12<00:11, 1402.00it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  54%|███▊   | 17536/32563 [00:12<00:10, 1367.16it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  55%|███▊   | 17792/32563 [00:13<00:10, 1372.71it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  56%|███▉   | 18304/32563 [00:13<00:09, 1433.90it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  57%|███▉   | 18560/32563 [00:13<00:09, 1427.11it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  59%|████   | 19072/32563 [00:13<00:09, 1433.99it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  59%|████▏  | 19328/32563 [00:14<00:09, 1421.84it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  61%|████▎  | 19840/32563 [00:14<00:08, 1423.71it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  62%|████▎  | 20096/32563 [00:14<00:08, 1442.70it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  63%|████▍  | 20608/32563 [00:14<00:08, 1449.28it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  64%|████▍  | 20864/32563 [00:15<00:08, 1436.92it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  66%|████▌  | 21376/32563 [00:15<00:07, 1444.96it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  66%|████▋  | 21632/32563 [00:15<00:07, 1434.97it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  68%|████▊  | 22144/32563 [00:16<00:07, 1466.78it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  69%|████▊  | 22400/32563 [00:16<00:06, 1456.54it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  70%|████▉  | 22912/32563 [00:16<00:06, 1451.84it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  71%|████▉  | 23168/32563 [00:16<00:06, 1472.55it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  73%|█████  | 23680/32563 [00:17<00:05, 1499.06it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  74%|█████▏ | 23936/32563 [00:17<00:05, 1494.58it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  75%|█████▎ | 24448/32563 [00:17<00:05, 1486.92it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  76%|█████▎ | 24704/32563 [00:17<00:05, 1477.87it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  77%|█████▍ | 25216/32563 [00:18<00:04, 1494.51it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  78%|█████▍ | 25472/32563 [00:18<00:04, 1498.65it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  79%|█████▌ | 25728/32563 [00:18<00:04, 1367.07it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  81%|█████▋ | 26240/32563 [00:18<00:04, 1402.53it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  81%|█████▋ | 26496/32563 [00:19<00:04, 1396.53it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  83%|█████▊ | 27008/32563 [00:19<00:03, 1451.32it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  84%|█████▊ | 27264/32563 [00:19<00:03, 1367.40it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  85%|█████▉ | 27520/32563 [00:19<00:04, 1172.40it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  85%|█████▉ | 27776/32563 [00:20<00:04, 1157.03it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  86%|██████ | 28032/32563 [00:20<00:04, 1123.10it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  87%|██████ | 28416/32563 [00:20<00:03, 1212.21it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  88%|██████▏| 28672/32563 [00:20<00:03, 1263.55it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  89%|██████▏| 28928/32563 [00:21<00:02, 1249.22it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  90%|██████▎| 29440/32563 [00:21<00:02, 1379.65it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  91%|██████▍| 29696/32563 [00:21<00:02, 1397.49it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  93%|██████▍| 30208/32563 [00:21<00:01, 1398.07it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  94%|██████▌| 30464/32563 [00:22<00:01, 1335.63it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  95%|██████▋| 30976/32563 [00:22<00:01, 1388.18it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  96%|██████▋| 31232/32563 [00:22<00:00, 1415.47it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  97%|██████▊| 31488/32563 [00:22<00:00, 1322.19it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  98%|██████▉| 32000/32563 [00:23<00:00, 1419.34it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001:  99%|██████▉| 32256/32563 [00:23<00:00, 1409.76it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([128, 42, 128])



Training - Epochs: 001/001: 100%|███████| 32563/32563 [00:23<00:00, 1373.16it/s]

EncoderBlock torch.Size([128, 42, 128])
EncoderBlock torch.Size([51, 42, 128])


In [26]:
import tqdm

correct = 0.0
total = 0.0
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pbar = tqdm.tqdm(total=len(test_loader.dataset))
model = SAnD(in_feature, seq_len, n_heads, factor, num_class, num_layers)
model = model.to(device)
criterion = nn.CrossEntropyLoss()
Y_pred= []
Y_true = []
for x, y in test_loader:
#     print("Here is type & shape", type(y), y.shape)
    b_size = y.shape[0]
    total += y.shape[0]
    x = x.to(device) if isinstance(x, torch.Tensor) else [i.to(device) for i in x]
    y = y.to(device)
    
    pbar.set_description("\033[32m"+"Evaluating"+"\033[0m")
    pbar.update(b_size)

    outputs = model(x)
#     print(outputs)
    idx = torch.argmax(outputs, dim=1) 
    print(idx)
#     _, predicted = torch.max(outputs, 1)
    Y_pred.append(idx)
    Y_true.append(y)

#     multilabel_auroc(predicted, y,num_labels=2, average="macro", thresholds=None)

Y_pred = np.concatenate(Y_pred, axis=0)
Y_true = np.concatenate(Y_true, axis=0)
# print(Y_pred)


Evaluating:  15%|███▉                      | 640/4188 [00:00<00:01, 2704.69it/s]

EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 


Evaluating:  28%|██████▉                  | 1152/4188 [00:00<00:01, 2738.56it/s]

tensor([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 1])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1


Evaluating:  43%|██████████▋              | 1792/4188 [00:00<00:00, 2723.06it/s]

tensor([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1])
EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1


Evaluating:  55%|█████████████▊           | 2304/4188 [00:00<00:00, 2749.54it/s]

EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 


Evaluating:  70%|█████████████████▌       | 2944/4188 [00:01<00:00, 2749.03it/s]

tensor([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0


Evaluating:  83%|████████████████████▋    | 3456/4188 [00:01<00:00, 2761.50it/s]

EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 1])
EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 


Evaluating:  98%|████████████████████████▍| 4096/4188 [00:01<00:00, 2785.38it/s]

tensor([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0])
EncoderBlock torch.Size([128, 42, 128])
tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1


Evaluating:  98%|████████████████████████▍| 4096/4188 [00:01<00:00, 2785.38it/s]

EncoderBlock torch.Size([92, 42, 128])
tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



Evaluating: 100%|█████████████████████████| 4188/4188 [00:12<00:00, 2785.38it/s]

In [27]:
from sklearn.metrics import roc_auc_score
roc_auc_score(
    Y_pred,
    Y_true,
    multi_class="raise",
    average="micro",
)

0.5062732151747232

In [28]:
from sklearn.metrics import precision_score, recall_score, auc, precision_recall_curve
p = precision_score(Y_true, Y_pred)
r = recall_score(Y_true, Y_pred)
p, r, thresholds1  = precision_recall_curve(Y_true, Y_pred)
auc_score = auc(r, p)
print(auc_score)

0.260012673938658
